dataUrl: http://media.juiceanalytics.com/census/CENSUS_STATEAGESEX.csv
skinName: white
levels: ["STATE", "SEX"]
colorField: POP2000
sizeField: POP2000
colorPalettes:
    - RdGy
    - Greens
remap:
    AGE:
        0: 0-9
        1: 0-9
        2: 0-9
        3: 0-9
        4: 0-9
        5: 0-9
        6: 0-9
        7: 0-9
        8: 0-9
        9: 0-9
